export const GET_DELIVERY_SUCCESS = 'GET_DELIVERY_SUCCESS';
export const DELIVERY_CREATE = 'CREATE_DELIVERY';
export const DELIVERY_DELETE = 'DELETE_DELIVERY';
export const DELIVERY_UPDATE = 'EDIT_DELIVERY';
export const DELIVERY_SELECT = 'SELECT_DELIVERY';
export const DELIVERY_RECOVER = 'DELIVERY_RECOVER';
export const SET_ORDER = 'SET_ORDER';

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RAISE_ERROR = 'RAISE_ERROR';
export const SIMULATE_API_CALL = 'SIMULATE_API_CALL';